#! /bin/sh

# init sxhkd
sxhkd &

bspc monitor DP-1 -d 'V' 'VI' 'VII' 'VII'
bspc monitor HDMI-1 -d 'I' 'II' 'III' 'IV'

# change monitor names
bspc monitor DP-1 -n sec
bspc monitor HDMI-1 -n pri

# focus on the primary desktop
bspc monitor -f pri


#bspc config border_width         2
bspc config window_gap          10

## Set the border colors.
bspc config focused_border_color "#00FF01"
